// src/components/experience/experience.vue
<template>
  <container>
    <div
      id="experience"
      class="container mt-8 mx-auto"
    >
      <section-title
        title="My resume"
        description="Professional Experience"
      />
      <card class="mx-auto">
        <div class="form bg-white p-4 my-5 relative mx-auto">
          <timeline :items="timelineItems" />
        </div>
      </card>
    </div>
  </container>
</template>

<script>
import {
  Container,
  Card,
  Timeline,
  SectionTitle,
} from 'UI-Components';
import workExperienceItems from './work-experience';

export default {
  components: {
    Container,
    Card,
    Timeline,
    SectionTitle,
  },
  data() {
    return {
      timelineItems: workExperienceItems,
    };
  },
};
</script>

<style lang="scss" scoped>
</style>

// src/components/Sections/experience.tsx
import { experiences } from '../../data/experiences'
import Container from '../ui/Container/Container'
import SectionDescription from '../ui/SectionDescription'
import Timeline from '../ui/Timeline'

const ServicesSection = () => {
  return (
    <Container id="experience">
      <SectionDescription
        title="Professional Experience"
        description="My Resume"
      />

      <div className="flex flex-col gap-4 max-w-screen-md">
        <Timeline items={experiences} />
      </div>
    </Container>
  )
}

export default ServicesSection
